version: '3.8'

networks:
  default-network:
    driver: bridge

services:
  api:
    build:
      dockerfile: Dockerfile_dev
      context: .
    env_file:
      - .envfile
    volumes:
      - .:/app/
    ports:
      - "5000:5000"
    networks:
      - default-network
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - .envfile
    networks:
        - default-network

  db-test:
    container_name: db-test
    image: postgres:13-alpine
    ports:
      - "54322:5432"
    env_file:
      - .envfile.test
    networks:
        - default-network

  api-test:
    build:
      dockerfile: Dockerfile_dev
      context: .
    env_file:
      - .envfile.test
    volumes:
      - .:/app/
    networks:
      - default-network
    depends_on:
      - db-test
    links:
      - db-test